export const ROSSO = {
  NAV: [["Servicios", "#servicios"], ["Nosotros", "#nosotros"], ["Flota", "#flota"], ["Trabajos", "#trabajos"], ["Contacto", "#contacto"]],
  SERVICES: [
    { id: "transporte", label: "Transporte", icon: "truck",
      title: "Transporte de maquinaria agrícola y pesada",
      copy: "Trasladamos cosechadoras, tractores, pulverizadoras y equipo vial en todo el país. Carretones de 3 a 6 ejes, escoltas y permisos de circulación gestionados por nosotros. Cada viaje sale con seguro de carga y seguimiento satelital.",
      specs: [["Capacidad", "hasta 80 t"], ["Ancho útil", "3,20 m"], ["Cobertura", "Todo el país"]] },
    { id: "montajes", label: "Montajes", icon: "wrench",
      title: "Montajes industriales llave en mano",
      copy: "Posicionamos y montamos líneas completas dentro de planta: silos, cintas, prensas y estructuras metálicas. Trabajamos con plan de izaje firmado, personal habilitado en altura y coordinación con el área de seguridad del cliente.",
      specs: [["Plan de izaje", "Incluido"], ["Personal", "Habilitado altura"], ["Paradas", "Nocturnas y fin de semana"]] },
    { id: "gruas", label: "Grúas", icon: "construction",
      title: "Servicio de grúa hidráulica",
      copy: "Grúas telescópicas de 25 a 120 toneladas con operadores propios. Resolvemos izajes puntuales, recambio de equipos y rescate de maquinaria en campo, con estudio de suelo previo cuando el terreno lo exige.",
      specs: [["Capacidad", "25 – 120 t"], ["Pluma", "hasta 62 m"], ["Disponibilidad", "24 / 7"]] },
    { id: "autoelevadores", label: "Autoelevadores", icon: "forklift",
      title: "Servicio de autoelevador",
      copy: "Autoelevadores de 2,5 a 16 toneladas para carga, descarga y movimiento interno de mercadería. Alquiler por jornada, por mes o con operador incluido, en depósito propio o en las instalaciones del cliente.",
      specs: [["Capacidad", "2,5 – 16 t"], ["Modalidad", "Con o sin operador"], ["Mínimo", "Media jornada"]] },
  ],
  STEPS: [
    ["01", "Relevamiento", "Vamos al lugar, medimos accesos y pesamos la carga. Sin relevamiento no hay presupuesto: preferimos ir una vez de más que improvisar en obra."],
    ["02", "Plan y permisos", "Ruta, escoltas, plan de izaje firmado y seguro de carga. Lo gestionamos nosotros y te llega en un solo parte, con fecha y ventana horaria."],
    ["03", "Operativo", "Equipo propio y operadores habilitados, un responsable en obra y parte diario al cierre de jornada. Si algo cambia, te enterás antes que nadie."],
  ],
  FLEET: [
    { name: "Carretón 4 ejes", specs: [["Carga", "45 t"], ["Piso", "Rebajado"], ["Ejes", "4 + dolly"]] },
    { name: "Carretón extensible", specs: [["Carga", "60 t"], ["Largo", "13 – 21 m"], ["Ejes", "6"]] },
    { name: "Grúa telescópica 70 t", specs: [["Pluma", "48 m"], ["Plumín", "16 m"], ["Contrapeso", "18 t"]] },
    { name: "Autoelevador 7 t", specs: [["Torre", "Triplex 4,8 m"], ["Combustible", "Diésel"], ["Uñas", "1,50 m"]] },
  ],
  WORKS: [
    { eyebrow: "Izaje", title: "Tótem de estación de servicio, con la playa abierta", image: "./assets/photos/izaje-totem.jpg", alt: "Grúa de Rosso Maquinarias colocando un tótem de estación de servicio al atardecer" },
    { eyebrow: "Mecanizado", title: "Un buje fuera de catálogo, torneado en once horas", image: "./assets/photos/torno-sm.jpg", alt: "Pieza de bronce torneada en el torno del taller" },
    { eyebrow: "Logística", title: "Veinticuatro pallets descargados sin frenar la planta", image: "./assets/photos/autoelevador.jpg", alt: "Autoelevador Rosso Maquinarias descargando pallets de un camión" },
  ],
  STATS: [["28", "años sobre la ruta"], ["140", "equipos por mes"], ["120 t", "de izaje máximo"], ["24/7", "guardia operativa"]],
  ABOUT: [
    ["Gente propia", "Choferes, operadores de grúa y personal de montaje en relación de dependencia, habilitados para trabajo en altura."],
    ["Taller propio", "Mantenimiento preventivo de carretones, grúas y autoelevadores en nuestras instalaciones, no tercerizado."],
    ["Papeles al día", "Permisos de circulación, escoltas, seguro de carga y ART al día para operar en planta o en ruta."],
    ["Un solo responsable", "Un referente por trabajo, de la cotización a la entrega. Sin transferencias entre áreas."],
  ],
  GOOGLE: { score: "4,8", scoreNum: 4.8, count: 63, href: "https://maps.google.com" },
  TESTIMONIALS: [
    { quote: "Nos movieron una cosechadora con el lote embarrado y la sacaron el mismo día. Avisaron cada paso por teléfono, sin que tengamos que llamar nosotros.", name: "Productor agropecuario", role: "Marcos Juárez, Córdoba" },
    { quote: "Coordinamos el izaje de dos silos en una parada de planta de fin de semana. Llegaron con el plan firmado y terminaron cuatro horas antes de la reapertura.", name: "Jefe de mantenimiento", role: "Industria alimenticia" },
    { quote: "Trabajamos con ellos hace seis años. La misma persona cotiza, coordina y atiende si algo se corre: eso vale más que el precio.", name: "Responsable de compras", role: "Metalúrgica, Santa Fe" },
  ],
};
